/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ControlPanel: typeof import('./components/ControlPanel.vue')['default']
    PinyinDisplay: typeof import('./components/PinyinDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingItem: typeof import('./components/SettingItem.vue')['default']
    SheetContainer: typeof import('./components/SheetContainer.vue')['default']
    SheetPreview: typeof import('./components/SheetPreview.vue')['default']
    StrokeDisplay: typeof import('./components/StrokeDisplay.vue')['default']
    ToggleSetting: typeof import('./components/ToggleSetting.vue')['default']
  }
}
