/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CharacterInfo: typeof import('./components/CharacterInfo.vue')['default']
    PinyinDisplay: typeof import('./components/PinyinDisplay.vue')['default']
    PinyinSheet: typeof import('./components/PinyinSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrokeAnimation: typeof import('./components/StrokeAnimation.vue')['default']
    StrokeDisplay: typeof import('./components/StrokeDisplay.vue')['default']
  }
}
